name: Build Naver Finance Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # 수동으로 워크플로우를 실행할 수 있는 옵션 추가

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # PyInstaller 설치
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile naver_finance_report.py
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: naver-finance-report
        path: dist/
