name: Python Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # 중지를 발생시키는 E9, F63, F7, F82만 체크하고 나머지는 경고만 표시
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
        
    - name: Build with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile naver_finance_report.py  # 여기서 your_main_script.py를 주 스크립트 파일명으로 변경하세요
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-app
        path: dist/
